version: '3.8'

services:
  postgres1:
    image: postgres:latest
    container_name: sample-store-postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    command: -c max_connections=200